In [ ]:
#importer les librairies
import numpy as np

**Exercice 1**

In [ ]:
#Constructeur un tableau numpy qui contient les éléments suivants : 1,5,7,8
np.array([1,5,7,8])

array([1, 5, 7, 8])

In [ ]:
#Constructeur un tableau numpy qui contient les éléments suivants :
1,2,3,4,5,6,7,8,9
np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
#Créer un tableau de 10 éléments rempli de 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#Créer un tableau de 2 lignes 5 colonnes rempli de 0
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Créer un tableau de 10 éléments rempli de 1
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
#Créer un tableau de 2 lignes 5 colonnes rempli de 1
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Créer un tableau de 10 éléments rempli 8.5
np.full(10,8.5)

array([8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5, 8.5])

In [ ]:
#Créer un tableau de série d'entiers successifs allant de 1 à 9 inclus
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#Créer un tableau de 3 lignes et 3 colonnes rempli de série d'entiers successifs
table =np.arange(1,10)
table.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Créer une matrice identité de 4 lignes 4 colonnes
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
#Tableau rempli de valeurs aléatoires normales centrées en zéro
np.random.rand(10)

array([0.65210327, 0.43141844, 0.8965466 , 0.36756187, 0.43586493,
       0.89192336, 0.80619399, 0.70388858, 0.10022689, 0.91948261])

In [ ]:
#Créer un tableau rempli de 20 valeurs aléatoires entières comprises entre 1 et 10
table_transform = np.random.randint(1,11,20)
table_transform

array([ 5,  3,  4,  6,  6,  3,  6,  8,  7,  1,  1,  8,  9,  8,  4,  4, 10,
        3,  7,  1])

In [ ]:
#Transformer le tableau précédent en matrice de 4 lignes et 5 colonnes
table_transform.reshape(4,5)

array([[ 5,  3,  4,  6,  6],
       [ 3,  6,  8,  7,  1],
       [ 1,  8,  9,  8,  4],
       [ 4, 10,  3,  7,  1]])

In [ ]:
#Créer un tableau de 5 éléments compris entre 0 et 1 avec une amplitude égale
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

**EXERCICE 2**

Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]]).


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Afficher le nombre de lignes et de colonnes
a.shape

(3, 3)

In [ ]:
 #Afficher la dimension de mon tableau
 a.ndim

2

In [ ]:
#Afficher le nombre d'élément de mon tableau
a.size

9

In [ ]:
#Afficher le type des éléments du tableau
a.dtype

dtype('int64')

**EXERCICE 3**

Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#afficher la valeur 5 qui est dans le tableau
a[1][1]

5

In [ ]:
#Remplacer le 5 qui est dans le tableau par 0
a[1][1]=0
a

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [ ]:
#afficher les chiffres 3, 6 et 9 du tableau
a[0:,2]

array([3, 6, 9])

In [ ]:
#créer un tableau de 4 lignes et 3 colonnes rempli de 12 nombres entiers aléatoires compris entre 0 et 9
tn =np.random.randint(0,10,12)
tn.reshape(4,3)

array([[2, 6, 8],
       [1, 9, 1],
       [7, 9, 7],
       [6, 5, 9]])

In [ ]:
#Vérifier qu’il y a des nombres inférieur à 5
np.any(tn<5)

True

In [ ]:
#Remplacer les nombres inférieurs à 5 par 0
np.where(tn<5,0, tn)

array([0, 6, 8, 0, 9, 0, 7, 9, 7, 6, 5, 9])

**EXERCICE 4**

In [ ]:
#Créer un tableau de 4 lignes et 3 colonnes rempli de 11 nombres entiers aléatoires compris entre 0 et 9
table_exo4=np.random.randint(0,10,(4,3))
table_exo4

array([[3, 3, 8],
       [1, 7, 3],
       [6, 8, 9],
       [7, 5, 3]])

In [ ]:
#Quel est le type des éléments du tableau ?
table_exo4.dtype

dtype('int64')

In [ ]:
# Changer de type des éléments du tableau en float32
table_exo4=np.float32(table_exo4)
table_exo4

array([[3., 3., 8.],
       [1., 7., 3.],
       [6., 8., 9.],
       [7., 5., 3.]], dtype=float32)

In [ ]:
#Ajouter le chiffre 3 à la fin du tableau à une dimension
table_exo4= np.append(table_exo4,3)
table_exo4

array([3., 3., 8., 1., 7., 3., 6., 8., 9., 7., 5., 3., 3.])

In [ ]:
#Transformer le tableau en matrice dénommée “a” de 3 lignes et 4 colonnes
a = table_exo4
a= np.delete(a,-1)
a=a.reshape(3,4)
a

array([[3., 3., 8., 1.],
       [7., 3., 6., 8.],
       [9., 7., 5., 3.]])

In [ ]:
#Créer une matrice dénommée “b” de 3 lignes et 4 colonnes remplie de série d'entiers successifs allant de 1 à 12 inclus
b= np.arange(1,13)
b= b.reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
# Créer une matrice dénommée “c” qui est la concaténation des deux tableaux “a” et “b” dans le sens horizontale
c=np.hstack((a,b))
c

array([[ 3.,  3.,  8.,  1.,  1.,  2.,  3.,  4.],
       [ 7.,  3.,  6.,  8.,  5.,  6.,  7.,  8.],
       [ 9.,  7.,  5.,  3.,  9., 10., 11., 12.]])

In [ ]:
#Créer une matrice dénommée “d” qui est la concaténation des deux tableaux “a” et “b” dans le sens verticale
d= np.vstack((a,b))
d

array([[ 3.,  3.,  8.,  1.],
       [ 7.,  3.,  6.,  8.],
       [ 9.,  7.,  5.,  3.],
       [ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [ ]:
#Aplatir un tableau “d”
d = np.ravel(d)
d

array([ 3.,  3.,  8.,  1.,  7.,  3.,  6.,  8.,  9.,  7.,  5.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [ ]:
#Supprimer dernier élément du tableau
d= np.delete(d,-1)
d

array([ 3.,  3.,  8.,  1.,  7.,  3.,  6.,  8.,  9.,  7.,  5.,  3.,  1.,
        2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

**EXERCICE 5**

Soit le tableau a = np.array([[1,2,3],[4,5,6],[7,8,9]])


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#Afficher la somme des éléments du tableau
a.sum()

45

In [ ]:
#Afficher la somme des éléments du tableau par colonne
a.sum(axis=0)

array([12, 15, 18])

In [ ]:
#Afficher la somme des éléments du tableau par ligne
a.sum(axis=1)

array([ 6, 15, 24])

In [ ]:
#Afficher le produit des éléments du tableau par colonne
prod= np.prod(a, axis=0)
prod

array([ 28,  80, 162])

In [ ]:
#Afficher le minimum du tableau
a.min()

1

In [ ]:
#Afficher le maximum des éléments du tableau
a.max()

9

In [ ]:
#Afficher le maximum des éléments du tableau
a.mean()

5.0

In [ ]:
# Afficher la variance des éléments du tableau
a.var()

6.666666666666667

In [ ]:
#Afficher l’écart type des éléments du tableau
a.std()

2.581988897471611